const mongoose = require("mongoose");

const pwaSchema = new mongoose.Schema(
  {
    adminId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
    },
    open: String,
    stayOn: String,
    add: String,
    clickIcon: String,
    pressIcon: String,
    step1ChromeDesktop: String,
    step2ChromeDesktop: String,
    step1SafariDesktop: String,
    step2SafariDesktop: String,
    step3SafariDesktop: String,
    step1ChromeMobile: String,
    step2ChromeMobile: String,
    step3ChromeMobile: String,
    step1SafariMobile: String,
    step2SafariMobile: String,
    step3SafariMobile: String,
    greeting: String,
    wait: String,
    proceed: String,
    description: String,
    containsAds: String,
    inAppPurchases: String,
    headerReviews: String,
    hundredPlus: String,
    downloads: String,
    ageLimit: String,
    ageRating: String,
    install: String,
    wishlist: String,
    available: String,
    aboutThisGame: String,
    about1: String,
    about2: String,
    about3: String,
    updatedOn: String,
    updatedDate: String,
    casino: String,
    dataSafety: String,
    safety: String,
    noInformation: String,
    seeDetails: String,
    ratingsAndReviews: String,
    verified: String,
    phone: String,
    tV: String,
    chromebook: String,
    tablet: String,
    reviews: String,
    fourPointThree: String,
    fifteenM: String,
    review1: String,
    review2: String,
    review3: String,
    review4: String,
    allReviews: String,
    whatsNew: String,
    findHelpful: String,
    yes: String,
    no: String,
    contact: String,
  },
  { timestamps: true }
);

const Pwa = mongoose.model("Pwa", pwaSchema);
module.exports = Pwa;
